### PR TITLE
(NPUP-5) Refactor function dispatch to use type system.

### PR DESCRIPTION
**Pull request by peterhuene**
This refactors function dispatch to make use of the Puppet type system to
describe the function signatures and validate argument types.  It
also makes the dispatcher dynamic in the sense that new functions can be
registered at runtime; this will be needed to implement functions written in
the Puppet language in the future.

The dispatcher now makes use of function descriptors: a descriptor represents a
single function and has dispatch descriptors that describe an overload's
signature and a callback to invoke if the signature matches.

Descriptors contain logic of finding a matching overload and invoking it.  If
the function call could not be dispatched, a check is done for invalid argument
counts, block parameter counts, or argument types and an exception is thrown. This
makes it so that individual functions don't have to do repetitive validating of
all their arguments.

Note that individual function implementations have transitioned from having to
visit their arguments so that desired overload can be deduced to simply having
dedicated callbacks for a particular overload.

This may be extended for operator dispatch in the future.

### CODE REVIEW

**Comment by peterhuene** [comment]
The last commit is going to be very difficult to review.  For the most part, the functions have been modified to move their visitor implementations into stand-alone functions that are simply invoked when the function is called (parameter validation happens before the callback is invoked now).  The meat of the change is `lib/src/compiler/evaluation/functions/descriptor.cc` that both describes a function and performs call validation before invoking an overload's callback.

**Comment by hlindberg** [comment]
I like the idea of extending this ad use it also for operator dispatch.

**Comment by hlindberg** [comment]
There was a pattern to the last commit, so not that bad to review as it first looked. (I obviously did not review the impl of each and every function as I expect that we later will have comprehensive test suite for all kinds of evaluation and each function in detail). Using the puppet type system makes it a lot more readable, and it looks like a reduction in code in the functions as well.

Merging.

**Comment by peterhuene** [comment]
Awesome, thanks for the review on this Henrick, as I know it was not an easy one.  I will probably put up a PR to refactor operator dispatch this week as well; I will endeavor to make it much easier to review.

**Comment by hlindberg** [comment]
:-) This is like learning a human language by deep immersion... "If you are hungry you better learn how to ask for food".

**Comment by hlindberg** [comment]
Regarding the missing newline. Was it supposed to be one there? In any case, no need to PR that change alone, just push it directly with a (maint) commit (or same PUP as this).

**Pull request merged**
